"""SHADE -- Success-History based Adaptive DE (Assignment 1.3).

Extends JADE with a historical memory of successful F/CR pairs for parameter
control. Owner: Dev B.

Need a historical memory set containing H pairs of successful crossover rates and scale factors.
During each generation, parameter values are generated by randomly selecting an entry index k from memory
with CR drawn from a normal distribytion and F from a cauchy distribution.

The historical memory is dynamically updated at the end of
each generation using the weighted Lehmer mean for scale factors, and the weighted arithmetic mean for
crossover rates based on fitness improvement.
"""

from __future__ import annotations

from .base import BaseOptimizer, OptResult
import numpy as np


class SHADE(BaseOptimizer):
    name = "SHADE"

    def __init__(self, *args, H: int | None = None, p_max: float = 0.2, **kwargs):
        super().__init__(*args, **kwargs)
        self.H = H if H is not None else self.pop_size
        self.p_max = p_max

    def optimize(self) -> OptResult:  # noqa: D401

        #Initialize population, memory and archive
        N, D = self.pop_size, self.dim
        pop = self.lower + self.rng.random((N, D)) * (self.upper - self.lower)
        fit = np.array([self.fitness(x) for x in pop])
        evals = N

        M_CR = np.full(self.H, 0.5)
        M_F = np.full(self.H, 0.5)
        k = 0
        archive: list[np.ndarray] = []
        history = [fit.max()]

        #Sample CR and F for every individual in the population
        while evals < self.max_fes:
            r = self.rng.integers(0, self.H, N)
            CR = np.clip(self.rng.normal(M_CR[r], 0.1), 0.0, 1.0)

            F = M_F[r] + 0.1 * self.rng.standard_cauchy(N)
            while np.any(F <= 0):
                bad = F <= 0
                F[bad] = M_F[r][bad] + 0.1 * self.rng.standard_cauchy(bad.sum())
            F = np.minimum(F, 1.0)

            #Mutation and current-to-pbest with archive
            order = np.argsort(-fit) #best first
            new_pop, new_fit = pop.copy(), fit.copy()
            S_CR, S_F, dF = [], [], []

            union = np.vstack([pop] + [np.array(archive)] if archive else [pop])

            for i in range(N):
                if evals >= self.max_fes:
                    break

                p = self.rng.uniform(2 / N, self.p_max)
                n_p = max(2, int(round(p * N)))
                pbest = pop[order[self.rng.integers(0, n_p)]]

                r1 = self.rng.choice([j for j in range(N) if j != i])
                
                while True:
                    r2 = self.rng.integers(0, len(union))
                    if r2 != i and r2 != r1:
                        break

                v = pop[i] + F[i] * (pbest - pop[i]) + F[i] * (pop[r1] - union[r2])

                #Bound handling
                lo, hi = v < self.lower, v > self.upper
                v[lo] = (self.lower[lo] + pop[i][lo]) / 2
                v[hi] = (self.upper[hi] + pop[i][hi]) / 2

                #Binomial crossover
                mask = self.rng.random(D) < CR[i]
                mask[self.rng.integers(0, D)] = True
                u = np.where(mask, v, pop[i])

                #Evaluate and select
                fu = self.fitness(u)
                evals += 1
                if fu >= fit[i]:
                    if fu > fit[i]:
                        S_CR.append(CR[i])
                        S_F.append(F[i])
                        dF.append(fu - fit[i])
                        archive.append(pop[i].copy())

                    new_pop[i], new_fit[i] = u, fu

            pop, fit = new_pop, new_fit

            #Trim archive
            while len(archive) > N:
                archive.pop(self.rng.integers(0, len(archive)))

            #Update memory
            if S_CR:
                w = np.array(dF) / np.sum(dF)
                S_CR, sF = np.array(S_CR), np.array(S_F)
                M_CR[k] = np.sum(w * S_CR)
                M_F[k] = np.sum(w * sF**2) / np.sum(w * sF)
                k = (k + 1) % self.H

            history.append(fit.max())

        best = np.argmax(fit)
        return OptResult(pop[best].copy(), float(fit[best]), history, evals)
